
export const subjects = [
    
  {
    id: "123",
    title: "Banana",
    level: "3",
    description: "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. ",
    video: " ",
    question: "What is a banana?",
    answer1: "Banana is edible and botanically it is a berry.",
    answer2: "The banana is a fruit from the citrus.",
    correctAnswer: "Banana is edible and botanically it is a berry.",
  },
  {
    id: "124",
    title: "Fisch",
    level: "1",
    description: "Fish are aquatic, craniate, gill-bearing animals that lack limbs with digits.",
    video: " ",
    question: "Are fisches terrestrial or acuatic animal?",
    answer1: "They are acuatic.",
    answer2: "They are terrestrial.",
    correctAnswer: "They are is acuatic.",
  },
  {
    id: "125",
    title: "Sun",
    level: "",
    description: " ",
    video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "126",
    title: "A",
    level: "",
    description: " ",
    video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "127",
    title: "B",
    level: "",
    description: " ",
     video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  
  ];
  