
export const subjects = [
  {
    id: "1",
    title: "Technology",
    level: "3",
    description: "",
    image:";",
    video: " ",
    question: "Who founded the company Apple Inc.?",
    answer1: "Steve Jobs.",
    answer2: " Bill Gates.",
    correctAnswer: "Steve Jobs.",
  },
  {
    id: "2",
    title: "Art",
    level: "3",
    description: " ",
    image: "./../public/Images/Art.jpeg",
    video: "https://youtu.be/AYtA7UHay6g",
    question: " Who painted the famous artwork Starry Night?",
    answer1: "Vincent Van Gogh.",
    answer2: " Pablo Picasso.",
    correctAnswer: "Vincent Van Gogh.",
  },
  {
    id: "3",
    title: "Math",
    level: "3",
    description: " ",
    video: " ",
    question: "What is the value of pi (π) to two decimal places?",
    answer1: "3.16.",
    answer2: "3.14.",
    correctAnswer: "3.14.",
  },
  {
    id: "21",
    title: "Chemistry",
    level: "3",
    description: " ",
    video: " ",
    question: "What is the most abundant gas in Earth's atmosphere?",
    answer1: "Nitrogen.",
    answer2: "Oxygen.",
    correctAnswer: "Nitrogen.",
  },
{
    id: "4",
    title: "Education",
    level: "2",
    description: "",
    video: " ",
    question: "What is the term for the type of education that is conducted over the internet?",
    answer1: "Distance education.",
    answer2: "Online learning.",
    correctAnswer: "Online learning.",
  },
  {
    id: "5",
    title: "Astronomy",
    level: "4",
    description: " ",
    video: " ",
    question: "What is the term for the process by which a star exhausts its fuel and collapses under its own gravity?",
    answer1: "Supernova.",
    answer2: " Black hole",
    correctAnswer: "Supernova.",
  },
  {
    id: "6",
    title: "Astronomy",
    level: "2",
    description: " ",
    video: " ",
    question: "What is the closest planet to the Sun in our solar system?",
    answer1: "Venus.",
    answer2: "Mercury.",
    correctAnswer: "Mercury.",
  },
  {
    id: "7",
    title: "Fish",
    level: "1",
    description: "Fish are aquatic, craniate, gill-bearing animals that lack limbs with digits.",
    video: " ",
    question: "Are fishes terrestrial or acuatic animal?",
    answer1: "They are terrestrial.",
    answer2: "They are acuatic.",
    correctAnswer: "They are is acuatic.",
  },
  {
    id: "8",
    title: "Sun",
    level: "1",
    description: " ",
    video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    id: "9",
    title: "A",
    level: "2",
    description: " ",
    video: " ",
    question: "What is the psychological term for the fear of spiders?",
    answer1: "Arachnophobia.",
    answer2: "Agoraphobia.",
    correctAnswer: "Arachnophobia.",
  },
  {
    id: "10",
    title: "Biology",
    level: "3",
    description: " ",
    video: " ",
    question: "What is the primary function of red blood cells in the human body?",
    answer1: "To remove waste products from the body's tissues.",
    answer2: "To transport oxygen from the lungs to the body's tissues.",
    correctAnswer: "To transport oxygen from the lungs to the body's tissues.",
  },
  {
    id: "11",
    title: "Science",
    level: "3",
    description: " ",
    video: " ",
    question: "What is the smallest unit of matter?",
    answer1: "Cell.",
    answer2: " Atom.",
    correctAnswer: " Atom.",
  },
  {
    id: "12",
    title: "Banana",
    level: "2",
    description: "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. ",
    video: " ",
    question: "What is a banana?",
    answer1: "Banana is edible and botanically it is a berry.",
    answer2: "The banana is a fruit from the citrus.",
    correctAnswer: "Banana is edible and botanically it is a berry.",
  },
  
  {
    id: "13",
    title: "Environmental Science",
    level: "3",
    description: " ",
    video: " ",
    question: "What is the term for the gradual increase in the Earth's average surface temperature?",
    answer1: " Global warming.",
    answer2: "Climate change.",
    correctAnswer: " Global warming.",
  },
  {
    id: "14",
    title: "Chemistry",
    level: "4",
    description: " ",
    video: " ",
    question: " What is the term for a substance that speeds up a chemical reaction?",
    answer1: " Catalyst.",
    answer2: " Enzyme.",
    correctAnswer: "Enzyme.",
  },
  {
    id: "15",
    title: "Astronomy",
    level: "4",
    description: " ",
    video: " ",
    question: "What is the term for the process by which a star exhausts its fuel and collapses under its own gravity?",
    answer1: "Supernova.",
    answer2: " Black hole",
    correctAnswer: "Supernova.",
  },
  {
    id: "16",
    title: "Marketing",
    level: "3",
    description: "",
    video: " ",
    question: "What is the term for the use of social media to promote a product or service?",
    answer1: "Social media marketing.",
    answer2: "Influencer marketing.",
    correctAnswer: "Social media marketing.",
  },
  {
    id: "17",
    title: "Journalism",
    level: "3",
    description: " ",
    video: " ",
    question: "What is the term for the deliberate spreading of false information with the intention of misleading people?",
    answer1: "Propaganda.",
    answer2: "Fake news.",
    correctAnswer: "Fake news.",
  },
  {
    id: "18",
    title: "Physics",
    level: "3",
    description: " ",
    video: " ",
    question: "What is the fundamental force that causes objects to fall towards the ground?",
    answer1: "Gravity.",
    answer2: "Electromagnetism.",
    correctAnswer: "Gravity.",
  },
  {
    id: "19",
    title: "Psychology",
    level: "2",
    description: " ",
    video: " ",
    question: "What is the term for the ability to understand and share the feelings of others?",
    answer1: "Empathy.",
    answer2: "Sympathy.",
    correctAnswer: "Empathy.",
  },
  {
    id: "20",
    title: "Physics",
    level: "4",
    description: " ",
    video: " ",
    question: "What is the unit of measurement for electrical resistance?",
    answer1: "Ohm.",
    answer2: "Ampere.",
    correctAnswer: "Ohm.",
  },
  ];
  