
export const subjects = [
  {
    topic: "art",
    description: " ",
    video: "https://youtu.be/AYtA7UHay6g",
    question: " Who painted the famous artwork Starry Night?",
    answer1: "Vincent Van Gogh.",
    answer2: " Pablo Picasso.",
    correctAnswer: "Vincent Van Gogh.",
  },
  {
    topic: "technology",
    description: "",
    video: "",
    question: "Who founded the company Apple Inc.?",
    answer1: "Steve Jobs.",
    answer2: " Bill Gates.",
    correctAnswer: "Steve Jobs.",
  },
  {
    topic: "math",
    description: " ",
    video: " ",
    question: "What is the value of pi (π) to two decimal places?",
    answer1: "3.16.",
    answer2: "3.14.",
    correctAnswer: "3.14.",
  },
  {
    topic: "chemistry",
    description: " ",
    image: "",
    video: "https://youtu.be/Rd4a1X3B61w",
    question: "What is the most abundant gas in Earth's atmosphere?",
    answer1: "Nitrogen.",
    answer2: "Oxygen.",
    correctAnswer: "Nitrogen.",
  },
  {
    topic: "education",
    description: "",
    video: " ",
    question: "What is the term for the type of education that is conducted over the internet?",
    answer1: "Distance education.",
    answer2: "Online learning.",
    correctAnswer: "Online learning.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What was the name of the mission launched by NASA in November 2018 to study the interior of Mars?",
    answer1: "InSight.",
    answer2: "Curiosity.",
    correctAnswer: "InSight.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the closest planet to the Sun in our solar system?",
    answer1: "Venus.",
    answer2: "Mercury.",
    correctAnswer: "Mercury.",
  },
  {
    topic: "fish",
    description: "Fish are aquatic, craniate, gill-bearing animals that lack limbs with digits.",
    video: " ",
    question: "Are fishes terrestrial or acuatic animal?",
    answer1: "They are terrestrial.",
    answer2: "They are acuatic.",
    correctAnswer: "They are acuatic.",
  },
  {
    topic: "sun",
    description: " ",
    video: " ",
    question: "Is the Sun a planet or a star?",
    answer1: "It is a star.",
    answer2: "It is a planet.",
    correctAnswer: "It is a star.",
  },
  {
    topic: "psycology",
    description: " ",
    video: " ",
    question: "What is the psychological term for the fear of spiders?",
    answer1: "Arachnophobia.",
    answer2: "Agoraphobia.",
    correctAnswer: "Arachnophobia.",
  },
  {
    topic: "biology",
    description: " ",
    video: " ",
    question: "What is the primary function of red blood cells in the human body?",
    answer1: "To remove waste products from the body's tissues.",
    answer2: "To transport oxygen from the lungs to the body's tissues.",
    correctAnswer: "To transport oxygen from the lungs to the body's tissues.",
  },
  {
    topic: "science",
    description: " ",
    video: " ",
    question: "What is the smallest unit of matter?",
    answer1: "Cell.",
    answer2: " Atom.",
    correctAnswer: " Atom.",
  },
  {
    topic: "banana",
    description: "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. ",
    video: " ",
    question: "What is a banana?",
    answer1: "Banana is edible and botanically it is a berry.",
    answer2: "The banana is a fruit from the citrus.",
    correctAnswer: "Banana is edible and botanically it is a berry.",
  },
  
  {
    topic: "environmental",
    description: " ",
    video: " ",
    question: "What is the term for the gradual increase in the Earth's average surface temperature?",
    answer1: " Global warming.",
    answer2: "Climate change.",
    correctAnswer: " Global warming.",
  },
  {
    topic: "chemistry",
    description: " ",
    video: " ",
    question: " What is the term for a substance that speeds up a chemical reaction?",
    answer1: " Catalyst.",
    answer2: " Enzyme.",
    correctAnswer: "Enzyme.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the term for the process by which a star exhausts its fuel and collapses under its own gravity?",
    answer1: "Supernova.",
    answer2: " Black hole",
    correctAnswer: "Supernova.",
  },
  {
    topic: "marketing",
    description: "",
    video: " ",
    question: "What is the term for the use of social media to promote a product or service?",
    answer1: "Social media marketing.",
    answer2: "Influencer marketing.",
    correctAnswer: "Social media marketing.",
  },
  {
    topic: "journalism",
    description: " ",
    video: " ",
    question: "What is the term for the deliberate spreading of false information with the intention of misleading people?",
    answer1: "Propaganda.",
    answer2: "Fake news.",
    correctAnswer: "Fake news.",
  },
  {
    topic: "physics",
    description: " ",
    video: " ",
    question: "What is the fundamental force that causes objects to fall towards the ground?",
    answer1: "Gravity.",
    answer2: "Electromagnetism.",
    correctAnswer: "Gravity.",
  },
  {
    topic: "psychology",
    description: " ",
    video: " ",
    question: "What is the term for the ability to understand and share the feelings of others?",
    answer1: "Empathy.",
    answer2: "Sympathy.",
    correctAnswer: "Empathy.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the Big Bang?",
    answer1: "The initial explosion that resulted in the formation of the universe.",
    answer2: "The formation of Earth from dust and gas in space.",
    correctAnswer: "The initial explosion that resulted in the formation of the universe.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is a planet?",
    answer1: " A natural satellite that orbits a planet.",
    answer2: "A celestial body that orbits a star and is not a satellite of a planet.",
    correctAnswer: "A celestial body that orbits a star and is not a satellite of a planet.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is a black hole?",
    answer1: "A celestial body that emits light and heat.",
    answer2: "A region of space where gravity is so strong that nothing can escape.",
    correctAnswer: "A region of space where gravity is so strong that nothing can escape.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the name of the closest star to Earth?",
    answer1: "Alpha Centauri.",
    answer2: "Sirius.",
    correctAnswer: "Alpha Centauri.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "Which planet in our solar system is known for its rings?",
    answer1: "Saturn.",
    answer2: "Mars.",
    correctAnswer: "Saturn.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the name of the largest moon of Saturn?",
    answer1: " Titan.",
    answer2: "Europa.",
    correctAnswer: "Europa.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the name of the galaxy that contains our solar system?",
    answer1: "Milky Way.",
    answer2: "Andromeda.",
    correctAnswer: "Milky Way.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What was the primary objective of the Juno mission launched by NASA in 2011?",
    answer1: "To study Mars.",
    answer2: "To study Jupiter.",
    correctAnswer: "To study Jupiter.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What was the name of the first satellite launched into orbit?",
    answer1: " Sputnik 1.",
    answer2: "Explorer 1.",
    correctAnswer: " Sputnik 1.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What was the purpose of the Apollo 11 mission?",
    answer1: "To study the geology of Mars.",
    answer2: "To land humans on the Moon for the first time.",
    correctAnswer: "To land humans on the Moon for the first time.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "In what year did the Hubble Space Telescope launch?",
    answer1: "1990.",
    answer2: "1980.",
    correctAnswer: "1990.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the name of the force that keeps planets in orbit around the sun?",
    answer1: "Gravity.",
    answer2: "Magnetism.",
    correctAnswer: "Gravity.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What was the purpose of NASA's Curiosity mission?",
    answer1: "To search for signs of past or present microbial life on Mars.",
    answer2: "To explore the Gale crater on Mars.",
    correctAnswer: "To explore the Gale crater on Mars.",
  },
  {
    topic: "astronomy",
    description: " ",
    video: " ",
    question: "What is the name of the asteroid belt located between Mars and Jupiter?",
    answer1: " Kuiper Belt.",
    answer2: "Asteroid Belt.",
    correctAnswer: "Asteroid Belt.",
  },
 
  {
    topic: "",
    description: " ",
    video: " ",
    question: "",
    answer1: "",
    answer2: "",
    correctAnswer: "",
  },
  

];